require'plugins.paq-nvim'
require'plugins.nvim-lspconfig.index'
require'plugins.nvim-cmp'
require'plugins.vim-polyglot'
require'plugins.lualine'
require'plugins.nvim-colorizer'
require'plugins.fzf-lua'
require'plugins.nvim-tree'
