require 'paq' {
  'farmergreg/vim-lastplace';
  'hoob3rt/lualine.nvim';
  'hrsh7th/cmp-buffer';
  'hrsh7th/cmp-nvim-lsp';
  'hrsh7th/cmp-vsnip';
  'hrsh7th/nvim-cmp';
  'hrsh7th/vim-vsnip';
  'ibhagwan/fzf-lua';
  'kyazdani42/nvim-web-devicons';
  'kyazdani42/nvim-tree.lua';
  'morhetz/gruvbox';
  'neovim/nvim-lspconfig';
  'norcalli/nvim-colorizer.lua';
  'savq/paq-nvim';
  'sheerun/vim-polyglot';
  'tpope/vim-commentary';
  'tpope/vim-surround';
  'tpope/vim-eunuch';
  'tpope/vim-repeat';
  'tpope/vim-fugitive';
  'vijaymarupudi/nvim-fzf';
  'Yggdroot/indentLine';
}
